name: mysql

on:
  workflow_dispatch:

env:
  MYSQL_MAJOR: 5.7

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Debug Action
        uses: hmarr/debug-action@v1.0.0
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./build-context
          file: Dockerfile
          build-args: MYSQL_MAJOR=${{ env.MYSQL_MAJOR }}
          platforms: linux/arm/v7,linux/amd64
          push: true
          tags: |
            wagoautomation/mysql:${{ env.MYSQL_MAJOR }}
            wagoautomation/mysql:latest
